<?php

/**
 * @file
 * Primary module hooks for Logo per language module.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StreamWrapper\StreamWrapperManager;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lpl_form_system_theme_settings_alter(&$form, FormStateInterface $form_state, $form_id = NULL) {
  // logo per language
  $languages = \Drupal::config('language.negotiation')->get('url.prefixes');
  $language_entities = \Drupal::languageManager()->getLanguages();
  $theme = str_replace('.settings', '', $form['config_key']['#value']);

  foreach ($languages as $key => $language) {
    if (!empty($language)) {
      // define array keys.
      $logo_key = 'logo_' . $key;
      $logo_settings_key = $logo_key . '_settings';
      $logo_default_key = 'lpl_default_logo_' . $key;
      $logo_path_key = 'lpl_' . $key . '_logo_path';
      $logo_upload_key = 'lpl_' . $key . '_logo_upload';

      // clone logo form item.
      $form[$logo_key] = $form['logo'];
      $form[$logo_key]['#title'] = 'Logo - ' . $language_entities[$key]->getName();
      $form[$logo_key][$logo_default_key] = $form[$logo_key]['default_logo'];
      $form[$logo_key][$logo_default_key]['#default_value'] = theme_get_setting($logo_default_key, $theme);
      unset($form[$logo_key]['default_logo']);

      // change cloned form item keys.
      $form[$logo_key][$logo_settings_key] = $form[$logo_key]['settings'];
      $form[$logo_key][$logo_settings_key][$logo_path_key] = $form[$logo_key]['settings']['logo_path'];
      $form[$logo_key][$logo_settings_key][$logo_path_key]['#default_value'] = theme_get_setting($logo_path_key, $theme);
      $form[$logo_key][$logo_settings_key][$logo_path_key]['#description'] = $form['logo']['settings']['logo_path']['#description'];
      $form[$logo_key][$logo_settings_key][$logo_upload_key] = $form[$logo_key]['settings']['logo_upload'];
      // set validation extensions.
      $form[$logo_key][$logo_settings_key][$logo_upload_key]['#upload_validators'] = [
        'file_validate_extensions' => ['gif png jpg jpeg svg'],
      ];
      $form[$logo_key][$logo_settings_key][$logo_upload_key]['#default_value'] = theme_get_setting($logo_upload_key, $theme);
      $form[$logo_key][$logo_settings_key][$logo_upload_key]['#upload_location'] = \Drupal::config('system.file')->get('default_scheme') . '://theme/logo_per_language/';

      $form[$logo_key][$logo_settings_key]['#states']['invisible'] = [
        'input[name="' . $logo_default_key . '"]' => [
          'checked' => TRUE,
        ],
      ];

      // Unset unwanted items.
      unset($form[$logo_key]['settings']);
      unset($form[$logo_key][$logo_settings_key]['logo_path']);
      unset($form[$logo_key][$logo_settings_key]['logo_upload']);
    }
  }

  $form['#validate'][] = 'logo_per_language_validate';
}

/**
 * Validates submission values in the FORM_ID() form.
 */
function logo_per_language_validate(array &$form, FormStateInterface $form_state) {
  // logo per language
  $languages = \Drupal::config('language.negotiation')->get('url.prefixes');
  $language_entities = \Drupal::languageManager()->getLanguages();

  foreach ($languages as $key => $language) {
  if (!empty($language)) {
    $logo_path_key = 'lpl_' . $key . '_logo_path';

    if (!empty($form_state->getValue($logo_path_key))) {
      if (!validatePath($form_state->getValue($logo_path_key))) {
        $form_state->setErrorByName($logo_path_key, t('The custom logo path is invalid.'));
        }
      }
    }
  }
}

/**
 * Helper function for the system_theme_settings form.
 *
 * Attempts to validate normal system paths, paths relative to the public files
 * directory, or stream wrapper URIs. If the given path is any of the above,
 * returns a valid path or URI that the theme system can display.
 *
 * @param string $path
 *   A path relative to the Drupal root or to the public files directory, or
 *   a stream wrapper URI.
 *
 * @return mixed
 *   A valid path that can be displayed through the theme system, or FALSE if
 *   the path could not be validated.
 */
function validatePath($path) {
  // Absolute local file paths are invalid.
  if (\Drupal::service('file_system')->realpath($path) == $path) {
    return FALSE;
  }
  // A path relative to the Drupal root or a fully qualified URI is valid.
  if (is_file($path)) {
    return $path;
  }
  // Prepend 'public://' for relative file paths within public filesystem.
  if (StreamWrapperManager::getScheme($path) === FALSE) {
    $path = 'public://' . $path;
  }
  if (is_file($path)) {
    return $path;
  }
  return FALSE;
}

/**
 * Implements hook_preprocess_block().
 */
function lpl_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] == 'system_branding_block') {
    $variables['#cache']['contexts'][] = 'languages:language_interface';
    $languages = \Drupal::config('language.negotiation')->get('url.prefixes');
    $current_langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();

    if (!empty($languages[$current_langcode]) && theme_get_setting('lpl_default_logo_' . $current_langcode) == 0) {
      if (!empty(theme_get_setting('lpl_' . $current_langcode . '_logo_path'))) {
        $variables['content']['site_logo']['#uri'] = '/' . theme_get_setting('lpl_' . $current_langcode . '_logo_path');
      }
      elseif (!empty('lpl_' . $current_langcode . '_logo_upload')) {
        $fid = theme_get_setting('lpl_' . $current_langcode . '_logo_upload');
        if (!empty($fid[0])) {
          $file = File::load($fid[0]);
          if (!is_null($file)) {
            $variables['content']['site_logo']['#uri'] = $file->createFileUrl();
          }
        }
      }
    }
  }
}
