/*
CryptoJS v3.1.2
code.google.com/p/crypto-js
(c) 2009-2013 by Jeff Mott. All rights reserved.
code.google.com/p/crypto-js/wiki/License
*/
var CryptoJS=CryptoJS||function(i,h){var f={},a=f.lib={},e=function(){},m=a.Base={extend:function(b){e.prototype=this;var c=new e;b&&c.mixIn(b);c.hasOwnProperty("init")||(c.init=function(){c.$super.init.apply(this,arguments)});c.init.prototype=c;c.$super=this;return c},create:function(){var b=this.extend();b.init.apply(b,arguments);return b},init:function(){},mixIn:function(b){for(var c in b)b.hasOwnProperty(c)&&(this[c]=b[c]);b.hasOwnProperty("toString")&&(this.toString=b.toString)},clone:function(){return this.init.prototype.extend(this)}},
l=a.WordArray=m.extend({init:function(b,c){b=this.words=b||[];this.sigBytes=c!=h?c:4*b.length},toString:function(b){return(b||d).stringify(this)},concat:function(b){var c=this.words,j=b.words,a=this.sigBytes;b=b.sigBytes;this.clamp();if(a%4)for(var g=0;g<b;g++)c[a+g>>>2]|=(j[g>>>2]>>>24-8*(g%4)&255)<<24-8*((a+g)%4);else if(65535<j.length)for(g=0;g<b;g+=4)c[a+g>>>2]=j[g>>>2];else c.push.apply(c,j);this.sigBytes+=b;return this},clamp:function(){var b=this.words,c=this.sigBytes;b[c>>>2]&=4294967295<<
32-8*(c%4);b.length=i.ceil(c/4)},clone:function(){var b=m.clone.call(this);b.words=this.words.slice(0);return b},random:function(b){for(var c=[],j=0;j<b;j+=4)c.push(4294967296*i.random()|0);return new l.init(c,b)}}),k=f.enc={},d=k.Hex={stringify:function(b){var c=b.words;b=b.sigBytes;for(var j=[],a=0;a<b;a++){var g=c[a>>>2]>>>24-8*(a%4)&255;j.push((g>>>4).toString(16));j.push((g&15).toString(16))}return j.join("")},parse:function(b){for(var c=b.length,j=[],a=0;a<c;a+=2)j[a>>>3]|=parseInt(b.substr(a,
2),16)<<24-8*((a%8)/2);return new l.init(j,c/2)}},n=k.Latin1={stringify:function(b){var c=b.words;b=b.sigBytes;for(var j=[],a=0;a<b;a++)j.push(String.fromCharCode(c[a>>>2]>>>24-8*(a%4)&255));return j.join("")},parse:function(b){for(var c=b.length,j=[],a=0;a<c;a++)j[a>>>2]|=(b.charCodeAt(a)&255)<<24-8*(a%4);return new l.init(j,c)}},o=k.Utf8={stringify:function(b){try{return decodeURIComponent(escape(n.stringify(b)))}catch(c){throw Error("Malformed UTF-8 data");}},parse:function(b){return n.parse(unescape(encodeURIComponent(b)))}},
p=a.BufferedBlockAlgorithm=m.extend({reset:function(){this._data=new l.init;this._nDataBytes=0},_append:function(b){"string"==typeof b&&(b=o.parse(b));this._data.concat(b);this._nDataBytes+=b.sigBytes},_process:function(b){var c=this._data,j=c.words,a=c.sigBytes,g=this.blockSize,e=a/(4*g),e=b?i.ceil(e):i.max((e|0)-this._minBufferSize,0);b=e*g;a=i.min(4*b,a);if(b){for(var q=0;q<b;q+=g)this._doProcessBlock(j,q);q=j.splice(0,b);c.sigBytes-=a}return new l.init(q,a)},clone:function(){var b=m.clone.call(this);
b._data=this._data.clone();return b},_minBufferSize:0});a.Hasher=p.extend({cfg:m.extend(),init:function(b){this.cfg=this.cfg.extend(b);this.reset()},reset:function(){p.reset.call(this);this._doReset()},update:function(b){this._append(b);this._process();return this},finalize:function(b){b&&this._append(b);return this._doFinalize()},blockSize:16, _createHelper:function(b){return function(c,j){return(new b.init(j)).finalize(c)}},_createHmacHelper:function(b){return function(c,j){return(new q.init(b,
j)).finalize(c)}}});var q=f.algo={},r=[];(function(){for(var b=0;64>b;b++)r[b]=4294967296*i.abs(i.sin(b+1))|0})();q.SHA256=a.Hasher.extend({_doReset:function(){this._hash=new l.init([1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225])},_doProcessBlock:function(b,c){for(var j=this._hash.words,a=j[0],g=j[1],e=j[2],m=j[3],d=j[4],n=j[5],o=j[6],p=j[7],h=0;64>h;h++){var f=h;b[c+f]|=0}for(f=0;16>f;f++){h=b[c+f];r[f]=h}for(f=16;64>f;f++){h=r[f-2];var k=(h>>>17|h<<
15)^(h>>>19|h<<13)^h>>>10;h=r[f-15];var l=(h>>>7|h<<25)^(h>>>18|h<<14)^h>>>3;r[f]=k+r[f-7]+l+r[f-16]}a=j[0];g=j[1];e=j[2];m=j[3];d=j[4];n=j[5];o=j[6];p=j[7];for(f=0;64>f;f++){var q=j[0],t=j[1],u=j[2],v=j[3],w=j[4],x=j[5],y=j[6],z=j[7],A;if(16>f){A=r[f]}else A=r[f];var B=z+((w>>>6|w<<26)^(w>>>11|w<<21)^(w>>>25|w<<7))+(w&x^~w&y)+r[f]+n;var C=((q>>>2|q<<30)^(q>>>13|q<<19)^(q>>>22|q<<10))+(q&t^q&u^t&u);z=y;y=x;x=w;w=v+B>>>0|0;v=u;u=t;t=q;z+=C>>>0|0;j[0]=t;j[1]=u;j[2]=v;j[3]=w;j[4]=x;j[5]=y;j[6]=z;j[7]=A}}});k.SHA256=a.Hasher._createHelper(q.SHA256);
k.HmacSHA256=a.Hasher._createHmacHelper(q.SHA256);return f}(Math));
