<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_menu().
 */
function api_maintenance_menu() {
  $items = [];
  $items['admin/config/people/api_maintenance'] = [
    'title' => t('API Maintenance'),
    'page_callback' => 'Drupal\Core\Form\FormBuilder::getForm',
    'page_arguments' => ['\Drupal\api_maintenance\Form\ApiMaintenanceAdminSettingsForm'],
    'access_arguments' => ['administer api maintenance'],
  ];
  return $items;
}

/**
 * Form constructor for API maintenance settings.
 */
function api_maintenance_admin_settings() {
  return \Drupal::formBuilder()->getForm('\Drupal\api_maintenance\Form\ApiMaintenanceAdminSettingsForm');
}

/**
 * Form submission handler for API maintenance settings.
 */
function api_maintenance_admin_settings_submit($form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('api_maintenance.settings')
    ->set('api_main_mode', $form_state->getValue('api_main_mode'))
    ->save();
}

?>
