<?php

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_form_alter().
 */
function shipmatesearch_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form_state->get('view')->id() == 'shipmates') {
    if ($form['#id'] == 'views-exposed-form-shipmates-page') {
      $form['field_date_of_commission_value']['value']['#date_format'] = 'd/m/Y';
      $form['field_date_of_retirement_value']['value']['#date_format'] = 'd/m/Y';
      $form['actions']['submit'] = [
        '#type' => 'submit',
        '#name' => 'searchredirect',
        '#title' => 'Search Keyword',
        '#submit' => ['search_redirect'],
        '#value' => t('Search'),
      ];
    }
    if ($form['#id'] == 'views-exposed-form-shipmates-page-2') {
      $form['field_date_of_commission_value']['value']['#date_format'] = 'd/m/Y';
      $form['field_date_of_retirement_value']['value']['#date_format'] = 'd/m/Y';
    }
  }
}

/**
 * Submit callback for search redirection.
 */
function search_redirect(array &$form, FormStateInterface $form_state) {
  $request = \Drupal::request();
  if ($form_state->getValue('searchredirect')) {
    $query_string = $request->getQueryString();
    $redirect_path = Url::fromUri('base:' . $request->getBaseUrl() . '/shipmate?' . $query_string);
    $form_state->setRedirectUrl($redirect_path);
  }
}
