<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;

/**
 * Implements hook_form_FORM_ID_alter() for user_login_form.
 */
function login_page_links_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $options = [
      'attributes' => [
        'title' => t('Register'),
      ],
    ];
    $form['actions']['submit']['#suffix'] = '<div class="forgotPassMain"><div id="forgotPass"><a title="' . t('Forgot Password') . '" href="/member/password">' . t('Forgot Password') . '</a></div><div id="user_register">' . t('New User? ') . Link::fromTextAndUrl(t('Register'), \Drupal\Core\Url::fromRoute('user.register', [], $options)) . "</div></div>";
  }
}
?>
